C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.21.1)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywraperf_c (erf_cf2pywrap, xx)
      external erf_c
      real xx
      real erf_cf2pywrap, erf_c
      erf_cf2pywrap = erf_c(xx)
      end


      subroutine f2pywrapfermid (fermidf2pywrap, xx)
      external fermid
      real xx
      real fermidf2pywrap, fermid
      fermidf2pywrap = fermid(xx)
      end


      subroutine f2pywrapdelthm (delthmf2pywrap, xx)
      external delthm
      real xx
      real delthmf2pywrap, delthm
      delthmf2pywrap = delthm(xx)
      end


      subroutine f2pywrapspline (splinef2pywrap, x)
      external spline
      real x
      real splinef2pywrap, spline
      splinef2pywrap = spline(x)
      end


      subroutine f2pywrapposhm (poshmf2pywrap, x)
      external poshm
      real x
      real poshmf2pywrap, poshm
      poshmf2pywrap = poshm(x)
      end


      subroutine f2pywrapposhm2 (poshm2f2pywrap, x)
      external poshm2
      real x
      real poshm2f2pywrap, poshm2
      poshm2f2pywrap = poshm2(x)
      end


      subroutine f2pyinitwarn(setupfunc)
      external setupfunc
      integer iwarn
      common /warn/ iwarn
      call setupfunc(iwarn)
      end
