/* File: efermi_modulemodule.c
 * This file is auto-generated with f2py (version:1.21.1).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Jul 21 04:01:37 2021
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *efermi_module_error;
static PyObject *efermi_module_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = efermi_module_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj, 0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = efermi_module_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}

static int
float_from_pyobj(float* v, PyObject *obj, const char *errmess)
{
    double d=0.0;
    if (double_from_pyobj(&d,obj,errmess)) {
        *v = (float)d;
        return 1;
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(efermi,EFERMI)(int*,int*,float*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,float*,int*);
extern void F_WRAPPEDFUNC_US(erf_c,ERF_C)(float*,float*);
extern void F_WRAPPEDFUNC(fermid,FERMID)(float*,float*);
extern void F_WRAPPEDFUNC(delthm,DELTHM)(float*,float*);
extern void F_WRAPPEDFUNC(spline,SPLINE)(float*,float*);
extern void F_WRAPPEDFUNC(poshm,POSHM)(float*,float*);
extern void F_WRAPPEDFUNC(poshm2,POSHM2)(float*,float*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** efermi ***********************************/
static char doc_f2py_rout_efermi_module_efermi[] = "\
occ,ef,sort,eigmin,eigmax,enocc = efermi(nel,nbands,del,nsppts,weight,ef,eigval,ismear)\n\nWrapper for ``efermi``.\
\n\nParameters\n----------\n"
"nel : input int\n"
"nbands : input int\n"
"del : input float\n"
"nsppts : input int\n"
"weight : input rank-1 array('f') with bounds (nsppts)\n"
"ef : input float\n"
"eigval : input rank-2 array('f') with bounds (nsppts,nbands)\n"
"ismear : input int\n"
"\nReturns\n-------\n"
"occ : rank-2 array('f') with bounds (nsppts,nbands)\n"
"ef : float\n"
"sort : rank-1 array('f') with bounds (nsppts*nbands)\n"
"eigmin : float\n"
"eigmax : float\n"
"enocc : float";
/* extern void F_FUNC(efermi,EFERMI)(int*,int*,float*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,float*,int*); */
static PyObject *f2py_rout_efermi_module_efermi(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,float*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,float*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  int nel = 0;
  PyObject *nel_capi = Py_None;
  int nbands = 0;
  PyObject *nbands_capi = Py_None;
  float del = 0;
  PyObject *del_capi = Py_None;
  int nsppts = 0;
  PyObject *nsppts_capi = Py_None;
  int ndim8 = 0;
  int ndim10 = 0;
  float *weight = NULL;
  npy_intp weight_Dims[1] = {-1};
  const int weight_Rank = 1;
  PyArrayObject *capi_weight_tmp = NULL;
  int capi_weight_intent = 0;
  PyObject *weight_capi = Py_None;
  float *occ = NULL;
  npy_intp occ_Dims[2] = {-1, -1};
  const int occ_Rank = 2;
  PyArrayObject *capi_occ_tmp = NULL;
  int capi_occ_intent = 0;
  float ef = 0;
  PyObject *ef_capi = Py_None;
  float *eigval = NULL;
  npy_intp eigval_Dims[2] = {-1, -1};
  const int eigval_Rank = 2;
  PyArrayObject *capi_eigval_tmp = NULL;
  int capi_eigval_intent = 0;
  PyObject *eigval_capi = Py_None;
  float *sort = NULL;
  npy_intp sort_Dims[1] = {-1};
  const int sort_Rank = 1;
  PyArrayObject *capi_sort_tmp = NULL;
  int capi_sort_intent = 0;
  float eigmin = 0;
  float eigmax = 0;
  float enocc = 0;
  int ismear = 0;
  PyObject *ismear_capi = Py_None;
    static char *capi_kwlist[] = {"nel","nbands","del","nsppts","weight","ef","eigval","ismear",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOO|:efermi_module.efermi",\
        capi_kwlist,&nel_capi,&nbands_capi,&del_capi,&nsppts_capi,&weight_capi,&ef_capi,&eigval_capi,&ismear_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable nel */
    f2py_success = int_from_pyobj(&nel,nel_capi,"efermi_module.efermi() 1st argument (nel) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nbands */
    f2py_success = int_from_pyobj(&nbands,nbands_capi,"efermi_module.efermi() 2nd argument (nbands) can't be converted to int");
  if (f2py_success) {
  /* Processing variable del */
    f2py_success = float_from_pyobj(&del,del_capi,"efermi_module.efermi() 3rd argument (del) can't be converted to float");
  if (f2py_success) {
  /* Processing variable nsppts */
    f2py_success = int_from_pyobj(&nsppts,nsppts_capi,"efermi_module.efermi() 4th argument (nsppts) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ef */
    f2py_success = float_from_pyobj(&ef,ef_capi,"efermi_module.efermi() 6th argument (ef) can't be converted to float");
  if (f2py_success) {
  /* Processing variable eigmin */
  /* Processing variable eigmax */
  /* Processing variable enocc */
  /* Processing variable ismear */
    f2py_success = int_from_pyobj(&ismear,ismear_capi,"efermi_module.efermi() 8th argument (ismear) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndim8 */
  ndim8 = nbands;
  /* Processing variable ndim10 */
  ndim10 = nsppts;
  /* Processing variable weight */
  weight_Dims[0]=nsppts;
  capi_weight_intent |= F2PY_INTENT_IN;
  capi_weight_tmp = array_from_pyobj(NPY_FLOAT,weight_Dims,weight_Rank,capi_weight_intent,weight_capi);
  if (capi_weight_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : efermi_module_error,"failed in converting 5th argument `weight' of efermi_module.efermi to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    weight = (float *)(PyArray_DATA(capi_weight_tmp));

  /* Processing variable occ */
  occ_Dims[0]=nsppts,occ_Dims[1]=nbands;
  capi_occ_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_occ_tmp = array_from_pyobj(NPY_FLOAT,occ_Dims,occ_Rank,capi_occ_intent,Py_None);
  if (capi_occ_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : efermi_module_error,"failed in converting hidden `occ' of efermi_module.efermi to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    occ = (float *)(PyArray_DATA(capi_occ_tmp));

  /* Processing variable eigval */
  eigval_Dims[0]=nsppts,eigval_Dims[1]=nbands;
  capi_eigval_intent |= F2PY_INTENT_IN;
  capi_eigval_tmp = array_from_pyobj(NPY_FLOAT,eigval_Dims,eigval_Rank,capi_eigval_intent,eigval_capi);
  if (capi_eigval_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : efermi_module_error,"failed in converting 7th argument `eigval' of efermi_module.efermi to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    eigval = (float *)(PyArray_DATA(capi_eigval_tmp));

  /* Processing variable sort */
  sort_Dims[0]=nsppts*nbands;
  capi_sort_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_sort_tmp = array_from_pyobj(NPY_FLOAT,sort_Dims,sort_Rank,capi_sort_intent,Py_None);
  if (capi_sort_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : efermi_module_error,"failed in converting hidden `sort' of efermi_module.efermi to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    sort = (float *)(PyArray_DATA(capi_sort_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nel,&nbands,&del,&nsppts,&ndim8,&ndim10,weight,occ,&ef,eigval,sort,&eigmin,&eigmax,&enocc,&ismear);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NfNfff",capi_occ_tmp,ef,capi_sort_tmp,eigmin,eigmax,enocc);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_sort_tmp == NULL) ... else of sort*/
  /* End of cleaning variable sort */
  if((PyObject *)capi_eigval_tmp!=eigval_capi) {
    Py_XDECREF(capi_eigval_tmp); }
  }  /*if (capi_eigval_tmp == NULL) ... else of eigval*/
  /* End of cleaning variable eigval */
  }  /*if (capi_occ_tmp == NULL) ... else of occ*/
  /* End of cleaning variable occ */
  if((PyObject *)capi_weight_tmp!=weight_capi) {
    Py_XDECREF(capi_weight_tmp); }
  }  /*if (capi_weight_tmp == NULL) ... else of weight*/
  /* End of cleaning variable weight */
  /* End of cleaning variable ndim10 */
  /* End of cleaning variable ndim8 */
  } /*if (f2py_success) of ismear*/
  /* End of cleaning variable ismear */
  /* End of cleaning variable enocc */
  /* End of cleaning variable eigmax */
  /* End of cleaning variable eigmin */
  } /*if (f2py_success) of ef*/
  /* End of cleaning variable ef */
  } /*if (f2py_success) of nsppts*/
  /* End of cleaning variable nsppts */
  } /*if (f2py_success) of del*/
  /* End of cleaning variable del */
  } /*if (f2py_success) of nbands*/
  /* End of cleaning variable nbands */
  } /*if (f2py_success) of nel*/
  /* End of cleaning variable nel */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of efermi *******************************/

/*********************************** erf_c ***********************************/
static char doc_f2py_rout_efermi_module_erf_c[] = "\
erf_c = erf_c(xx)\n\nWrapper for ``erf_c``.\
\n\nParameters\n----------\n"
"xx : input float\n"
"\nReturns\n-------\n"
"erf_c : float";
/* extern void F_WRAPPEDFUNC_US(erf_c,ERF_C)(float*,float*); */
static PyObject *f2py_rout_efermi_module_erf_c(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  float erf_c = 0;
  float xx = 0;
  PyObject *xx_capi = Py_None;
    static char *capi_kwlist[] = {"xx",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:efermi_module.erf_c",\
        capi_kwlist,&xx_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable xx */
    f2py_success = float_from_pyobj(&xx,xx_capi,"efermi_module.erf_c() 1st argument (xx) can't be converted to float");
  if (f2py_success) {
  /* Processing variable erf_c */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&erf_c,&xx);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("f",erf_c);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable erf_c */
  } /*if (f2py_success) of xx*/
  /* End of cleaning variable xx */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of erf_c ********************************/

/*********************************** fermid ***********************************/
static char doc_f2py_rout_efermi_module_fermid[] = "\
fermid = fermid(xx)\n\nWrapper for ``fermid``.\
\n\nParameters\n----------\n"
"xx : input float\n"
"\nReturns\n-------\n"
"fermid : float";
/* extern void F_WRAPPEDFUNC(fermid,FERMID)(float*,float*); */
static PyObject *f2py_rout_efermi_module_fermid(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  float fermid = 0;
  float xx = 0;
  PyObject *xx_capi = Py_None;
    static char *capi_kwlist[] = {"xx",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:efermi_module.fermid",\
        capi_kwlist,&xx_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable xx */
    f2py_success = float_from_pyobj(&xx,xx_capi,"efermi_module.fermid() 1st argument (xx) can't be converted to float");
  if (f2py_success) {
  /* Processing variable fermid */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&fermid,&xx);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("f",fermid);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable fermid */
  } /*if (f2py_success) of xx*/
  /* End of cleaning variable xx */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of fermid *******************************/

/*********************************** delthm ***********************************/
static char doc_f2py_rout_efermi_module_delthm[] = "\
delthm = delthm(xx)\n\nWrapper for ``delthm``.\
\n\nParameters\n----------\n"
"xx : input float\n"
"\nReturns\n-------\n"
"delthm : float";
/* extern void F_WRAPPEDFUNC(delthm,DELTHM)(float*,float*); */
static PyObject *f2py_rout_efermi_module_delthm(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  float delthm = 0;
  float xx = 0;
  PyObject *xx_capi = Py_None;
    static char *capi_kwlist[] = {"xx",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:efermi_module.delthm",\
        capi_kwlist,&xx_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable xx */
    f2py_success = float_from_pyobj(&xx,xx_capi,"efermi_module.delthm() 1st argument (xx) can't be converted to float");
  if (f2py_success) {
  /* Processing variable delthm */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&delthm,&xx);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("f",delthm);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable delthm */
  } /*if (f2py_success) of xx*/
  /* End of cleaning variable xx */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of delthm *******************************/

/*********************************** spline ***********************************/
static char doc_f2py_rout_efermi_module_spline[] = "\
spline = spline(x)\n\nWrapper for ``spline``.\
\n\nParameters\n----------\n"
"x : input float\n"
"\nReturns\n-------\n"
"spline : float";
/* extern void F_WRAPPEDFUNC(spline,SPLINE)(float*,float*); */
static PyObject *f2py_rout_efermi_module_spline(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  float spline = 0;
  float x = 0;
  PyObject *x_capi = Py_None;
    static char *capi_kwlist[] = {"x",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:efermi_module.spline",\
        capi_kwlist,&x_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable x */
    f2py_success = float_from_pyobj(&x,x_capi,"efermi_module.spline() 1st argument (x) can't be converted to float");
  if (f2py_success) {
  /* Processing variable spline */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&spline,&x);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("f",spline);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable spline */
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of spline *******************************/

/*********************************** poshm ***********************************/
static char doc_f2py_rout_efermi_module_poshm[] = "\
poshm = poshm(x)\n\nWrapper for ``poshm``.\
\n\nParameters\n----------\n"
"x : input float\n"
"\nReturns\n-------\n"
"poshm : float";
/* extern void F_WRAPPEDFUNC(poshm,POSHM)(float*,float*); */
static PyObject *f2py_rout_efermi_module_poshm(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  float poshm = 0;
  float x = 0;
  PyObject *x_capi = Py_None;
    static char *capi_kwlist[] = {"x",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:efermi_module.poshm",\
        capi_kwlist,&x_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable x */
    f2py_success = float_from_pyobj(&x,x_capi,"efermi_module.poshm() 1st argument (x) can't be converted to float");
  if (f2py_success) {
  /* Processing variable poshm */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&poshm,&x);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("f",poshm);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable poshm */
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of poshm ********************************/

/*********************************** poshm2 ***********************************/
static char doc_f2py_rout_efermi_module_poshm2[] = "\
poshm2 = poshm2(x)\n\nWrapper for ``poshm2``.\
\n\nParameters\n----------\n"
"x : input float\n"
"\nReturns\n-------\n"
"poshm2 : float";
/* extern void F_WRAPPEDFUNC(poshm2,POSHM2)(float*,float*); */
static PyObject *f2py_rout_efermi_module_poshm2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  float poshm2 = 0;
  float x = 0;
  PyObject *x_capi = Py_None;
    static char *capi_kwlist[] = {"x",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:efermi_module.poshm2",\
        capi_kwlist,&x_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable x */
    f2py_success = float_from_pyobj(&x,x_capi,"efermi_module.poshm2() 1st argument (x) can't be converted to float");
  if (f2py_success) {
  /* Processing variable poshm2 */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&poshm2,&x);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("f",poshm2);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable poshm2 */
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of poshm2 *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_warn_def[] = {
  {"iwarn",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_warn(char *iwarn) {
  int i_f2py=0;
  f2py_warn_def[i_f2py++].data = iwarn;
}
extern void F_FUNC(f2pyinitwarn,F2PYINITWARN)(void(*)(char*));
static void f2py_init_warn(void) {
  F_FUNC(f2pyinitwarn,F2PYINITWARN)(f2py_setup_warn);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"efermi",-1,{{-1}},0,(char *)F_FUNC(efermi,EFERMI),(f2py_init_func)f2py_rout_efermi_module_efermi,doc_f2py_rout_efermi_module_efermi},
  {"erf_c",-1,{{-1}},0,(char *)F_WRAPPEDFUNC_US(erf_c,ERF_C),(f2py_init_func)f2py_rout_efermi_module_erf_c,doc_f2py_rout_efermi_module_erf_c},
  {"fermid",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(fermid,FERMID),(f2py_init_func)f2py_rout_efermi_module_fermid,doc_f2py_rout_efermi_module_fermid},
  {"delthm",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(delthm,DELTHM),(f2py_init_func)f2py_rout_efermi_module_delthm,doc_f2py_rout_efermi_module_delthm},
  {"spline",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(spline,SPLINE),(f2py_init_func)f2py_rout_efermi_module_spline,doc_f2py_rout_efermi_module_spline},
  {"poshm",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(poshm,POSHM),(f2py_init_func)f2py_rout_efermi_module_poshm,doc_f2py_rout_efermi_module_poshm},
  {"poshm2",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(poshm2,POSHM2),(f2py_init_func)f2py_rout_efermi_module_poshm2,doc_f2py_rout_efermi_module_poshm2},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "efermi_module",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};

PyMODINIT_FUNC PyInit_efermi_module(void) {
  int i;
  PyObject *m,*d, *s, *tmp;
  m = efermi_module_module = PyModule_Create(&moduledef);
  Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module efermi_module (failed to import numpy)"); return m;}
  d = PyModule_GetDict(m);
  s = PyUnicode_FromString("1.21.1");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString(
    "This module 'efermi_module' is auto-generated with f2py (version:1.21.1).\nFunctions:\n"
"  occ,ef,sort,eigmin,eigmax,enocc = efermi(nel,nbands,del,nsppts,weight,ef,eigval,ismear)\n"
"  erf_c = erf_c(xx)\n"
"  fermid = fermid(xx)\n"
"  delthm = delthm(xx)\n"
"  spline = spline(x)\n"
"  poshm = poshm(x)\n"
"  poshm2 = poshm2(x)\n"
"COMMON blocks:\n""  /warn/ iwarn\n"".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString("1.21.1");
  PyDict_SetItemString(d, "__f2py_numpy_version__", s);
  Py_DECREF(s);
  efermi_module_error = PyErr_NewException ("efermi_module.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "_efermi_module_error", efermi_module_error);
  Py_DECREF(efermi_module_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }


    {
      extern float F_FUNC_US(erf_c,ERF_C)(void);
      PyObject* o = PyDict_GetItemString(d,"erf_c");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC_US(erf_c,ERF_C),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("erf_c");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }


    {
      extern float F_FUNC(fermid,FERMID)(void);
      PyObject* o = PyDict_GetItemString(d,"fermid");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC(fermid,FERMID),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("fermid");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }


    {
      extern float F_FUNC(delthm,DELTHM)(void);
      PyObject* o = PyDict_GetItemString(d,"delthm");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC(delthm,DELTHM),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("delthm");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }


    {
      extern float F_FUNC(spline,SPLINE)(void);
      PyObject* o = PyDict_GetItemString(d,"spline");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC(spline,SPLINE),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("spline");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }


    {
      extern float F_FUNC(poshm,POSHM)(void);
      PyObject* o = PyDict_GetItemString(d,"poshm");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC(poshm,POSHM),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("poshm");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }


    {
      extern float F_FUNC(poshm2,POSHM2)(void);
      PyObject* o = PyDict_GetItemString(d,"poshm2");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC(poshm2,POSHM2),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("poshm2");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  tmp = PyFortranObject_New(f2py_warn_def,f2py_init_warn);
  F2PyDict_SetItemString(d, "warn", tmp);
  Py_DECREF(tmp);
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"efermi_module");
#endif
  return m;
}
#ifdef __cplusplus
}
#endif
