site_name: Solid State Standard Pseudopotential Toolkit
nav:
  - Home: index.md
  - Specification: spec.md
  - Web App: gui.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
