---
# Run basic tests for this app on the latest aiidalab-docker image.

name: continuous-integration

on: [push, pull_request]

jobs:

    pre-commit:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'

            - name: Install dependencies
              run: pip install -U pre-commit==2.10.0

            - name: Run pre-commit
              run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

    test:
        needs: [pre-commit]

        strategy:
            matrix:
                python-version: ['3.9']

        services:
            rabbitmq:
                image: rabbitmq:3.8.14-management
                ports:
                    - 5672:5672
                    - 15672:15672

        runs-on: ubuntu-latest
        timeout-minutes: 40

        steps:
            - uses: eWaterCycle/setup-singularity@v7 # for containerized code test
              with:
                  singularity-version: 3.8.7

            - uses: actions/checkout@v2

            - name: Cache Python dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.cache/pip
                  key: pip-${{ matrix.python-version }}-tests-${{ hashFiles('**/setup.json') }}
                  restore-keys: pip-${{ matrix.python-version }}-tests

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies for test
              run: |
                  pip install -U pip==22.3.1
                  pip install -U .[tests]

            # - name: Pull the image and Run pytest
            #   run: |
            #     singularity run docker://containers4hpc/qe-mpich314:0.1.0 which pw.x
            #     pytest -v tests/test_nightly.py -s
