---
# Run basic tests for this app on the latest aiidalab-docker image.

name: CI unit test

on: [push, pull_request]

jobs:


    fast-tests:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        services:
          rabbitmq:
            image: rabbitmq:3.8.14-management
            ports:
            - 5672:5672
            - 15672:15672

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install dependencies for test
              run: |
                  pip install .[dev]

            - name: Run pytest
              run: |
                  pytest -s tests -m "not slow"

    slow-tests:

        runs-on: ubuntu-latest
        timeout-minutes: 30

        services:
          rabbitmq:
            image: rabbitmq:3.8.14-management
            ports:
            - 5672:5672
            - 15672:15672

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install dependencies for test
              run: |
                  pip install .[dev]

            - name: Run pytest
              run: |
                  pytest -s tests -m "slow"

    edge-aiida-core-tests:
        # This is to test the plugin is compatible with the main branch of aiida-core

        needs: [slow-tests]
        runs-on: ubuntu-latest
        timeout-minutes: 30

        services:
          rabbitmq:
            image: rabbitmq:3.8.14-management
            ports:
            - 5672:5672
            - 15672:15672

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install dependencies and edge aiida-core for test
              run: |
                  pip install .[dev]
                  pip uninstall --yes aiida-core
                  git clone --depth 1 https://github.com/aiidateam/aiida-core.git
                  uv pip install ./aiida-core

            - name: Check aiida-core version is the edget ('post' in version tag)
              run: |
                  if verdi --version | grep -q "post"; then
                    echo $(verdi --version)
                  else
                    echo $(verdi --version)
                    exit 1
                  fi

            - name: Run pytest
              run: |
                  pytest -s tests
