name: Publish Python distributions 📦 to PyPI and TestPyPI

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Upgrade setuptools and install package
      run: |
        python -m pip install --upgrade pip
        pip install twine

    - name: Assert package version
      env:
        TAG_VERSION: ${{ github.ref }}
      run: python ./.github/check_version.py

    - name: Build source distribution
      uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2014_x86_64
      with:
        python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39'
        build-requirements: 'cython numpy'
        pip-wheel-args: '-w ./wheelhouse --no-deps'

    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload wheelhouse/*-manylinux*.whl
